### ISSUE TITLE
Blazeface tflite app references tflite_deeplab.h in the app_engine.h

### ISSUE THREAD

**Issue by Akhilesh-Gogikar** [terryky/android_tflite#2]
The blazeface app build fails because it reference a tflite_deeplab.h.

Where can I find the deeplab header file, and how does the app use that code?

Please explain. Eagerly waiting.

**Comment by terryky** [comment]
I've fixed it.
could you pull your repository and build again ?

**Comment by Akhilesh-Gogikar** [comment]
@terryky Sorry for the late check. I tried to build it and it did get build but the app doesn't work on my phone. I have a Google Pixel 2xl.

Let me know if it works on your phone or if I am doing something wrong.

**Comment by terryky** [comment]
I've confirmed that the blazeface app works on my Samsung galaxy S20 (Android 11).
I don't know why it does not work on your phone. 
Could you give me more information? Is there any log or message ?

**Comment by Akhilesh-Gogikar** [comment]
@terryky  I am closing it then most likely the GPU on the Pixel 2xl is messed up. I have had similar problems some AI inference apps don't work in my phone. Thanks.
