### ISSUE TITLE
add strip option to reduce size of .so files

### ISSUE THREAD

**Issue by soham24** [terryky/android_tflite#3]
--strip always
to bazel file.
also can you add script to generate arm .so file also ? with arm64

**Comment by terryky** [comment]
OK. I'll add --strip always option to build script.
BTW, why do you prefer the ```arm64``` option instead of current ```android_arm64``` ?

https://github.com/terryky/android_tflite/blob/7ec23458906ff81bacf6401ce655d9ba2135a0d6/third_party/build_libtflite_r2.4_android.sh#L42-L43

**Comment by soham24** [comment]
sorry I was being unclear. 

android_arm64 config builds .so file for arm64-v8a.
android_arm config builds .so file for armeabi-v7a.
It will be great if you add support for generating the second one.

**Comment by terryky** [comment]
Thank you for your explanation.
I understand your request and will add it to my TODO list.
